@echo off
setlocal enabledelayedexpansion

REM ================================================================
REM  Deploy DimensioneringV2 — stable or beta builds to X:\ drive
REM ================================================================
REM
REM  USAGE:
REM    deploy stable                         Build 'master', deploy to stable folder
REM    deploy beta                           Build 'feature/hydraulic-network', deploy to beta folder
REM    deploy beta feature/ga-optimization   Build specified branch, deploy to beta folder
REM    deploy both                           Deploy stable first, then beta
REM
REM  WHAT IT DOES:
REM    1. Stashes any uncommitted changes
REM    2. Checks out the target branch
REM    3. Builds Release configuration
REM    4. Copies output to X:\...\DimensioneringV2[-Beta]\
REM    5. Restores your original branch and stash
REM
REM  USERS IN AUTOCAD:
REM    Type NSDIMv2      -> loads stable  (master)
REM    Type NSDIMv2BETA  -> loads beta    (feature branch)
REM    Do NOT load both at the same time — command names will collide.
REM
REM  REQUIREMENTS:
REM    git, dotnet, robocopy, access to X:\ drive
REM    SharedAssemblies.Config.json must exist in deploy folders
REM    (generated by DevReload "Push to Production")
REM
REM  TO CHANGE DEFAULT BETA BRANCH:
REM    Edit the DEFAULT_BETA_BRANCH variable below
REM ================================================================

REM ── Configuration ───────────────────────────────────────────────
set "REPO_ROOT=%~dp0"
REM Remove trailing backslash
set "REPO_ROOT=%REPO_ROOT:~0,-1%"
set "PROJECT=%REPO_ROOT%\Acad-C3D-Tools\DimensioneringV2\DimensioneringV2.csproj"
set "BUILD_OUTPUT=%REPO_ROOT%\Acad-C3D-Tools\DimensioneringV2\bin\Release"
set "STABLE_BRANCH=master"
set "DEFAULT_BETA_BRANCH=feature/hydraulic-network"
set "DEPLOY_BASE=X:\AutoCAD DRI - 01 Civil 3D\NetloadV2\2025"
set "STABLE_DEPLOY=%DEPLOY_BASE%\DimensioneringV2"
set "BETA_DEPLOY=%DEPLOY_BASE%\DimensioneringV2-Beta"

REM ── Parse arguments ─────────────────────────────────────────────
if "%~1"=="" goto :help
if /i "%~1"=="help"   goto :help
if /i "%~1"=="-h"     goto :help
if /i "%~1"=="--help" goto :help
if /i "%~1"=="/?"     goto :help
set "MODE=%~1"
set "BETA_BRANCH=%DEFAULT_BETA_BRANCH%"
if not "%~2"=="" set "BETA_BRANCH=%~2"

if /i "%MODE%"=="stable" goto :start
if /i "%MODE%"=="beta"   goto :start
if /i "%MODE%"=="both"   goto :start
goto :help

REM ── Main ────────────────────────────────────────────────────────
:start

REM Save current branch
for /f "tokens=*" %%b in ('git -C "%REPO_ROOT%" rev-parse --abbrev-ref HEAD') do set "ORIGINAL_BRANCH=%%b"
set "STASHED=0"

REM Stash if dirty
git -C "%REPO_ROOT%" diff --quiet 2>nul
if errorlevel 1 (
    echo ^>^> Stashing uncommitted changes...
    git -C "%REPO_ROOT%" stash push -m "deploy-auto"
    set "STASHED=1"
) else (
    git -C "%REPO_ROOT%" diff --cached --quiet 2>nul
    if errorlevel 1 (
        echo ^>^> Stashing uncommitted changes...
        git -C "%REPO_ROOT%" stash push -m "deploy-auto"
        set "STASHED=1"
    )
)

if /i "%MODE%"=="stable" (
    call :deploy "%STABLE_BRANCH%" "%STABLE_DEPLOY%" "STABLE"
    if errorlevel 1 goto :restore
)
if /i "%MODE%"=="beta" (
    call :deploy "%BETA_BRANCH%" "%BETA_DEPLOY%" "BETA"
    if errorlevel 1 goto :restore
)
if /i "%MODE%"=="both" (
    call :deploy "%STABLE_BRANCH%" "%STABLE_DEPLOY%" "STABLE"
    if errorlevel 1 goto :restore
    call :deploy "%BETA_BRANCH%" "%BETA_DEPLOY%" "BETA"
    if errorlevel 1 goto :restore
)

echo.
echo === All done ===
goto :restore

REM ── Deploy function ─────────────────────────────────────────────
:deploy
set "BRANCH=%~1"
set "DEPLOY_TARGET=%~2"
set "LABEL=%~3"

echo.
echo === Deploy DimensioneringV2 (%LABEL%) ===
echo Branch: %BRANCH%
echo Target: %DEPLOY_TARGET%
echo.

echo ^>^> Checking out '%BRANCH%'...
git -C "%REPO_ROOT%" checkout %BRANCH% --quiet
if errorlevel 1 (
    echo ERROR: Failed to checkout '%BRANCH%'
    exit /b 1
)

echo ^>^> Building Release...
dotnet build "%PROJECT%" -c Release -p:WarningLevel=0
if errorlevel 1 (
    echo ERROR: Build failed
    exit /b 1
)

if not exist "%DEPLOY_TARGET%" mkdir "%DEPLOY_TARGET%"

echo ^>^> Copying files to %DEPLOY_TARGET%...
robocopy "%BUILD_OUTPUT%" "%DEPLOY_TARGET%" /E /IS /IT /R:2 /W:1 /NFL /NDL /NP /NJH /NJS
if %errorlevel% geq 8 (
    echo ERROR: Robocopy failed
    exit /b 1
)

echo ^>^> %LABEL% deploy complete.
exit /b 0

REM ── Restore original branch ────────────────────────────────────
:restore
echo.
echo ^>^> Restoring branch: %ORIGINAL_BRANCH%
git -C "%REPO_ROOT%" checkout %ORIGINAL_BRANCH% --quiet
if "%STASHED%"=="1" (
    echo ^>^> Popping stashed changes...
    git -C "%REPO_ROOT%" stash pop --quiet
)
endlocal
exit /b 0

REM ── Help ────────────────────────────────────────────────────────
:help
echo.
echo  Deploy DimensioneringV2 -- stable or beta builds to X:\ drive
echo  ================================================================
echo.
echo  USAGE:
echo    %~nx0 stable                         Build 'master', deploy to stable folder
echo    %~nx0 beta                           Build '%DEFAULT_BETA_BRANCH%', deploy to beta folder
echo    %~nx0 beta feature/ga-optimization   Build specified branch, deploy to beta folder
echo    %~nx0 both                           Deploy stable first, then beta
echo    %~nx0 help                           Show this help
echo.
echo  WHAT IT DOES:
echo    1. Stashes any uncommitted changes
echo    2. Checks out the target branch
echo    3. Builds Release configuration
echo    4. Copies output to X:\...\DimensioneringV2[-Beta]\
echo    5. Restores your original branch and stash
echo.
echo  USERS IN AUTOCAD:
echo    Type NSDIMv2      -^> loads stable  (master)
echo    Type NSDIMv2BETA  -^> loads beta    (feature branch)
echo    Do NOT load both at the same time -- command names will collide.
echo.
echo  REQUIREMENTS:
echo    git, dotnet, robocopy, access to X:\ drive
echo    SharedAssemblies.Config.json must exist in deploy folders
echo    (generated by DevReload "Push to Production")
echo.
echo  TO CHANGE DEFAULT BETA BRANCH:
echo    Edit the DEFAULT_BETA_BRANCH variable in this script
echo.
endlocal
exit /b 1
